/*

undefined
Remote request schema, e.g. how TSP should call MaaS-backend

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';
import * as Booking_ from 'src/core/booking';
import * as BookingOption_ from 'src/core/booking-option';

export const schemaId =
  'http://maasglobal.com/tsp/webhooks-bookings-update/remote-request.json';
// Default
// The purpose of this remains a mystery
export type Default = t.Branded<
  {
    tspId: Booking_.TspId;
    cost?: Booking_.Cost;
    state: 'RESERVED' | 'CONFIRMED' | 'ACTIVATED' | 'EXPIRED' | 'CANCELLED' | 'REJECTED';
    leg?: BookingOption_.LegDelta;
    meta?: Booking_.Meta;
    terms?: Booking_.Terms;
    token?: Booking_.Token;
  },
  DefaultBrand
>;
export const Default = t.brand(
  t.intersection([
    t.type({
      tspId: Booking_.TspId,
      state: t.union([
        t.literal('RESERVED'),
        t.literal('CONFIRMED'),
        t.literal('ACTIVATED'),
        t.literal('EXPIRED'),
        t.literal('CANCELLED'),
        t.literal('REJECTED'),
      ]),
    }),
    t.partial({
      cost: Booking_.Cost,
      leg: BookingOption_.LegDelta,
      meta: Booking_.Meta,
      terms: Booking_.Terms,
      token: Booking_.Token,
    }),
  ]),
  (
    x,
  ): x is t.Branded<
    {
      tspId: Booking_.TspId;
      cost?: Booking_.Cost;
      state:
        | 'RESERVED'
        | 'CONFIRMED'
        | 'ACTIVATED'
        | 'EXPIRED'
        | 'CANCELLED'
        | 'REJECTED';
      leg?: BookingOption_.LegDelta;
      meta?: Booking_.Meta;
      terms?: Booking_.Terms;
      token?: Booking_.Token;
    },
    DefaultBrand
  > => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}

export default Default;

// Success
