/*

Remote response schema, e.g. how MaaS-backend responds back to TSP

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';

export const schemaId = 'http://maasglobal.com/tsp/webhooks-bookings-update/remote-response.json';

