/*

undefined
MaaS customer personal data schema

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';
import * as Common_ from 'src/core/components/common';
import * as Address_ from 'src/core/components/address';
import * as Units_ from 'src/core/components/units';

export const schemaId = 'http://maasglobal.com/maas-backend/customers/personalData.json';
// Default
// The purpose of this remains a mystery
export type Default = t.Branded<
  {
    firstName?: Common_.PersonalName;
    lastName?: Common_.PersonalName;
    phone?: Common_.Phone;
    email?: Common_.Email;
    address?: Address_.Address;
    city?: Address_.City;
    country?: Address_.Country;
    zipCode?: Address_.ZipCode;
    dob?: boolean | Units_.IsoDate;
    ssid?: boolean | Common_.Ssid;
    subscriberType?: string;
  },
  DefaultBrand
>;
export const Default = t.brand(
  t.partial({
    firstName: Common_.PersonalName,
    lastName: Common_.PersonalName,
    phone: Common_.Phone,
    email: Common_.Email,
    address: Address_.Address,
    city: Address_.City,
    country: Address_.Country,
    zipCode: Address_.ZipCode,
    dob: t.union([t.boolean, Units_.IsoDate]),
    ssid: t.union([t.boolean, Common_.Ssid]),
    subscriberType: t.string,
  }),
  (
    x,
  ): x is t.Branded<
    {
      firstName?: Common_.PersonalName;
      lastName?: Common_.PersonalName;
      phone?: Common_.Phone;
      email?: Common_.Email;
      address?: Address_.Address;
      city?: Address_.City;
      country?: Address_.Country;
      zipCode?: Address_.ZipCode;
      dob?: boolean | Units_.IsoDate;
      ssid?: boolean | Common_.Ssid;
      subscriberType?: string;
    },
    DefaultBrand
  > => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}

export default Default;

// Success
