/*

undefined
Response schema for autocomplete

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';

export const schemaId =
  'http://maasglobal.com/maas-backend/autocomplete/autocomplete-query/response.json';
// Default
// The purpose of this remains a mystery
export type Default = t.Branded<
  {
    suggestions: [string];
    debug?: {};
  },
  DefaultBrand
>;
export const Default = t.brand(
  t.intersection([
    t.type({
      suggestions: t.tuple([t.string]),
    }),
    t.partial({
      debug: t.type({}),
    }),
  ]),
  (
    x,
  ): x is t.Branded<
    {
      suggestions: [string];
      debug?: {};
    },
    DefaultBrand
  > => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}

export default Default;

// Success
