/*

undefined
Response schema for subscriptions-create

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';
import * as Subscription_ from 'src/maas-backend/subscriptions/subscription';

export const schemaId =
  'http://maasglobal.com/maas-backend/subscriptions/subscriptions-create/response.json';
// Default
// The purpose of this remains a mystery
export type Default = t.Branded<
  {
    subscription: Subscription_.Subscription;
    debug?: {};
  },
  DefaultBrand
>;
export const Default = t.brand(
  t.intersection([
    t.type({
      subscription: Subscription_.Subscription,
    }),
    t.partial({
      debug: t.type({}),
    }),
  ]),
  (
    x,
  ): x is t.Branded<
    {
      subscription: Subscription_.Subscription;
      debug?: {};
    },
    DefaultBrand
  > => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}

export default Default;

// Success
