/*

undefined
Request schema for auth-sms-login

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';
import * as Common_ from 'src/core/components/common';
import * as ApiCommon_ from 'src/core/components/api-common';

export const schemaId =
  'http://maasglobal.com/maas-backend/auth/auth-sms-login/request.json';
// Default
// The purpose of this remains a mystery
export type Default = t.Branded<
  {
    payload: {
      phone: Common_.RawPhone;
      code: string;
    };
    headers?: ApiCommon_.Headers;
  },
  DefaultBrand
>;
export const Default = t.brand(
  t.intersection([
    t.type({
      payload: t.type({
        phone: Common_.RawPhone,
        code: t.string,
      }),
    }),
    t.partial({
      headers: ApiCommon_.Headers,
    }),
  ]),
  (
    x,
  ): x is t.Branded<
    {
      payload: {
        phone: Common_.RawPhone;
        code: string;
      };
      headers?: ApiCommon_.Headers;
    },
    DefaultBrand
  > => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}

export default Default;

// Success
