/*

undefined
Request schema for retrieving a ticket from booking through a TSP adapter

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';
import * as Booking_ from 'src/core/booking';

export const schemaId = 'http://maasglobal.com/tsp/bookings-ticket/request.json';
// Default
// The purpose of this remains a mystery
export type Default = t.Branded<
  {
    tspId: Booking_.TspId;
    ticket: string | Array<string>;
    token: Booking_.Token;
  },
  DefaultBrand
>;
export const Default = t.brand(
  t.type({
    tspId: Booking_.TspId,
    ticket: t.union([t.string, t.array(t.string)]),
    token: Booking_.Token,
  }),
  (
    x,
  ): x is t.Branded<
    {
      tspId: Booking_.TspId;
      ticket: string | Array<string>;
      token: Booking_.Token;
    },
    DefaultBrand
  > => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}

export default Default;

// Success
