/*

undefined
Schema for MODE_RAIL meta field

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';
import * as UnitsGeo_ from 'src/core/components/units-geo';
import * as Station_ from 'src/core/components/station';

export const schemaId = 'http://maasglobal.com/core/modes/MODE_RAIL.json';

export type Default = t.Branded<
  {
    outward?: {
      id?: string;
      from: UnitsGeo_.Place;
      to: UnitsGeo_.Place;
    };
    return?: {
      id?: string;
      from: UnitsGeo_.Place;
      to: UnitsGeo_.Place;
    };
    deliveryMethod?: {
      name?: string;
      stationId?: Station_.Id;
      alternativeCollections?: string;
    };
  },
  DefaultBrand
>;
export const Default = t.brand(
  t.partial({
    outward: t.intersection([
      t.type({
        from: UnitsGeo_.Place,
        to: UnitsGeo_.Place,
      }),
      t.partial({
        id: t.string,
      }),
    ]),
    return: t.intersection([
      t.type({
        from: UnitsGeo_.Place,
        to: UnitsGeo_.Place,
      }),
      t.partial({
        id: t.string,
      }),
    ]),
    deliveryMethod: t.partial({
      name: t.string,
      stationId: Station_.Id,
      alternativeCollections: t.string,
    }),
  }),
  (
    x,
  ): x is t.Branded<
    {
      outward?: {
        id?: string;
        from: UnitsGeo_.Place;
        to: UnitsGeo_.Place;
      };
      return?: {
        id?: string;
        from: UnitsGeo_.Place;
        to: UnitsGeo_.Place;
      };
      deliveryMethod?: {
        name?: string;
        stationId?: Station_.Id;
        alternativeCollections?: string;
      };
    },
    DefaultBrand
  > => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}
export default Default;
// Success
