/*

undefined
Schemas for MODE_CAR meta field

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as CarRental_ from 'src/core/components/car-rental';

export const schemaId = 'http://maasglobal.com/core/modes/MODE_CAR.json';
// Default
// The purpose of this remains a mystery
export type Default = CarRental_.Default;
export const Default = CarRental_.Default;

export default Default;

// Success
