/*

undefined
MaaS customer update

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';
import * as Customer_ from '../customer.json';

export const schemaId =
  'http://maasglobal.com/maas-backend/customers/update/response.json';
// Default
// The purpose of this remains a mystery
export type Default = t.Branded<
  {
    customer: Customer_.Default;
  },
  DefaultBrand
>;
export const Default = t.brand(
  t.type({
    customer: Customer_.Default,
  }),
  (
    x,
  ): x is t.Branded<
    {
      customer: Customer_.Default;
    },
    DefaultBrand
  > => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}

export default Default;

// Success
