/*

undefined
undefined

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as Response_ from 'src/tsp/stations-retrieve/response';

export const schemaId =
  'http://maasglobal.com/maas-backend/stations/stations-retrieve/response.json';
// Default
// The purpose of this remains a mystery
export type Default = Response_.Default;
export const Default = Response_.Default;

export default Default;

// Success
