/*

Response for MaaS webhook to receive payment status updates from payment gateways.

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';

export const schemaId = 'http://maasglobal.com/maas-backend/webhooks/webhooks-payments/response.json';

