/*

undefined
Response schema for completing customer authorization for TSP

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';
import * as Common_ from 'src/core/components/common';
import * as Units_ from 'src/core/components/units';
import * as Error_ from 'src/core/error';

export const schemaId = 'http://maasglobal.com/tsp/customer-auth-validate/response.json';
// Default
// The purpose of this remains a mystery
export type Default = t.Branded<
  {
    authToken?: Common_.EncodedQueryParam;
    validTo?: Units_.Time;
    nonce?: Common_.EncodedQueryParam;
    error?: Error_.Default;
  } & (unknown | unknown),
  DefaultBrand
>;
export const Default = t.brand(
  t.intersection([
    t.partial({
      authToken: Common_.EncodedQueryParam,
      validTo: Units_.Time,
      nonce: Common_.EncodedQueryParam,
      error: Error_.Default,
    }),
    t.union([t.unknown, t.unknown]),
  ]),
  (
    x,
  ): x is t.Branded<
    {
      authToken?: Common_.EncodedQueryParam;
      validTo?: Units_.Time;
      nonce?: Common_.EncodedQueryParam;
      error?: Error_.Default;
    } & (unknown | unknown),
    DefaultBrand
  > => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}

export default Default;

// Success
