/*

undefined
Response schema for itineraries-list

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';
import * as Itinerary_ from 'src/core/itinerary';

export const schemaId =
  'http://maasglobal.com/maas-backend/itineraries/itinerary-list/response.json';
// Default
// The purpose of this remains a mystery
export type Default = t.Branded<
  {
    itineraries: Array<Itinerary_.Default>;
    maas?: {};
  },
  DefaultBrand
>;
export const Default = t.brand(
  t.intersection([
    t.type({
      itineraries: t.array(Itinerary_.Default),
    }),
    t.partial({
      maas: t.type({}),
    }),
  ]),
  (
    x,
  ): x is t.Branded<
    {
      itineraries: Array<Itinerary_.Default>;
      maas?: {};
    },
    DefaultBrand
  > => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}

export default Default;

// Success
