/*

undefined
MaaS customer payment sources setup intent create

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';
import * as Units_ from 'src/core/components/units';
import * as Common_ from 'src/core/components/common';
import * as PaymentSource_ from 'src/maas-backend/customers/payment-sources/paymentSource';
import * as ApiCommon_ from 'src/core/components/api-common';

export const schemaId =
  'http://maasglobal.com/maas-backend/customers/payment-sources/setup-intent/request.json';
// Default
// The default export. More information at the top.
export type Default = t.Branded<
  {
    identityId: Units_.IdentityId;
    customerId: Units_.IdentityId;
    payload: {
      setupIntent: {
        paymentSourceId: Common_.PaymentSourceId;
        gatewayName: PaymentSource_.GatewayName;
        isDefault: boolean;
        type: PaymentSource_.Type;
        alias?: PaymentSource_.Alias;
      };
    };
    headers: ApiCommon_.Headers;
  },
  DefaultBrand
>;
export const Default = t.brand(
  t.type({
    identityId: Units_.IdentityId,
    customerId: Units_.IdentityId,
    payload: t.type({
      setupIntent: t.intersection([
        t.type({
          paymentSourceId: Common_.PaymentSourceId,
          gatewayName: PaymentSource_.GatewayName,
          isDefault: t.boolean,
          type: PaymentSource_.Type,
        }),
        t.partial({
          alias: PaymentSource_.Alias,
        }),
      ]),
    }),
    headers: ApiCommon_.Headers,
  }),
  (
    x,
  ): x is t.Branded<
    {
      identityId: Units_.IdentityId;
      customerId: Units_.IdentityId;
      payload: {
        setupIntent: {
          paymentSourceId: Common_.PaymentSourceId;
          gatewayName: PaymentSource_.GatewayName;
          isDefault: boolean;
          type: PaymentSource_.Type;
          alias?: PaymentSource_.Alias;
        };
      };
      headers: ApiCommon_.Headers;
    },
    DefaultBrand
  > => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}

export default Default;

// Success
