/*

MaaS Invoice schema

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';

export const schemaId = 'http://maasglobal.com/maas-backend/invoices/invoice.json';

export type InvoiceId = t.Branded<string, InvoiceIdBrand>
export const InvoiceId = t.brand(t.string, (x): x is t.Branded<string, InvoiceIdBrand> => x === x && (x.length >= 2), 'InvoiceId')
interface InvoiceIdBrand {
  readonly InvoiceId: unique symbol
}

