/*

undefined
MaaS push notification response schema.

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';
import * as Units_ from 'src/core/components/units';

export const schemaId =
  'http://maasglobal.com/maas-backend/push-notification/response.json';
// Default
// The default export. More information at the top.
export type Default = t.Branded<
  {
    identityId: Units_.IdentityId;
    results: unknown;
  },
  DefaultBrand
>;
export const Default = t.brand(
  t.type({
    identityId: Units_.IdentityId,
    results: t.unknown,
  }),
  (
    x,
  ): x is t.Branded<
    {
      identityId: Units_.IdentityId;
      results: unknown;
    },
    DefaultBrand
  > => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}

export default Default;

// Success
