/*

MaaS contact (customer and user) schema

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';
import * as Units_ from 'src/core/components/units';

export const schemaId = 'http://maasglobal.com/maas-backend/subscriptions/contact.json';

