/*

undefined
Request schema for bookings-create v2

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';
import * as Units_ from 'src/core/components/units';
import * as Common_ from 'src/core/components/common';
import * as Response_ from 'src/maas-backend/bookings/bookings-agency-options/response';
import * as CustomerSelection_ from 'src/core/components/customerSelection';
import * as ApiCommon_ from 'src/core/components/api-common';

export const schemaId =
  'http://maasglobal.com/maas-backend/bookings/v2/bookings-create/request.json';
// Default
// The purpose of this remains a mystery
export type Default = t.Branded<
  {
    identityId: Units_.IdentityId;
    payload: {
      paymentSourceId: Common_.PaymentSourceId;
      booking?: Response_.Option;
      customerSelection?: CustomerSelection_.Default;
    };
    headers?: ApiCommon_.Headers;
  },
  DefaultBrand
>;
export const Default = t.brand(
  t.intersection([
    t.type({
      identityId: Units_.IdentityId,
      payload: t.intersection([
        t.type({
          paymentSourceId: Common_.PaymentSourceId,
        }),
        t.partial({
          booking: Response_.Option,
          customerSelection: CustomerSelection_.Default,
        }),
      ]),
    }),
    t.partial({
      headers: ApiCommon_.Headers,
    }),
  ]),
  (
    x,
  ): x is t.Branded<
    {
      identityId: Units_.IdentityId;
      payload: {
        paymentSourceId: Common_.PaymentSourceId;
        booking?: Response_.Option;
        customerSelection?: CustomerSelection_.Default;
      };
      headers?: ApiCommon_.Headers;
    },
    DefaultBrand
  > => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}

export default Default;

// Success
