/*

undefined
Response schema for bookings-agency-products

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';
import * as Units_ from 'src/core/components/units';
import * as Fare_ from 'src/core/components/fare';
import * as Common_ from 'src/core/components/common';

export const schemaId =
  'http://maasglobal.com/maas-backend/bookings/bookings-agency-products/response.json';
// Product
// The purpose of this remains a mystery
export type Product = t.Branded<
  {
    id: string;
    agencyId: string;
    tspProductId: string;
    name: string;
    meta?: {};
    icon: Units_.Url;
    fares: Array<Fare_.Default>;
    description: string;
  },
  ProductBrand
>;
export const Product = t.brand(
  t.intersection([
    t.type({
      id: t.string,
      agencyId: t.string,
      tspProductId: t.string,
      name: t.string,
      icon: Units_.Url,
      fares: t.array(Fare_.Default),
      description: t.string,
    }),
    t.partial({
      meta: t.type({}),
    }),
  ]),
  (
    x,
  ): x is t.Branded<
    {
      id: string;
      agencyId: string;
      tspProductId: string;
      name: string;
      meta?: {};
      icon: Units_.Url;
      fares: Array<Fare_.Default>;
      description: string;
    },
    ProductBrand
  > => true,
  'Product',
);
export interface ProductBrand {
  readonly Product: unique symbol;
}
// Default
// The purpose of this remains a mystery
export type Default = t.Branded<
  {
    agencyId: Common_.AgencyId;
    products: Array<Product>;
  },
  DefaultBrand
>;
export const Default = t.brand(
  t.type({
    agencyId: Common_.AgencyId,
    products: t.array(Product),
  }),
  (
    x,
  ): x is t.Branded<
    {
      agencyId: Common_.AgencyId;
      products: Array<Product>;
    },
    DefaultBrand
  > => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}

export default Default;

// Success
