/*

undefined
Response schema for getting journey options from a TSP adapter.

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as Response_ from 'src/maas-backend/provider/routes/response';

export const schemaId = 'http://maasglobal.com/tsp/journey-planner/response.json';
// Default
// The purpose of this remains a mystery
export type Default = Response_.Default;
export const Default = Response_.Default;

export default Default;

// Success
