/*

undefined
Response schema for itinerary-retrieve

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';
import * as Itinerary_ from 'src/core/itinerary';

export const schemaId =
  'http://maasglobal.com/maas-backend/itineraries/itinerary-retrieve/response.json';
// Default
// The default export. More information at the top.
export type Default = t.Branded<
  {
    itinerary: Itinerary_.Default;
    maas?: {};
  },
  DefaultBrand
>;
export const Default = t.brand(
  t.intersection([
    t.type({
      itinerary: Itinerary_.Default,
    }),
    t.partial({
      maas: t.type({}),
    }),
  ]),
  (
    x,
  ): x is t.Branded<
    {
      itinerary: Itinerary_.Default;
      maas?: {};
    },
    DefaultBrand
  > => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}

export default Default;

// Success
