/*

undefined
Response schema for getting options from a TSP adapter

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';
import * as BookingOption_ from 'src/core/booking-option';
import * as BikeStation_ from 'src/core/components/bike-station';

export const schemaId = 'http://maasglobal.com/tsp/bookings-options-list/response.json';
// Default
// The purpose of this remains a mystery
export type Default = t.Branded<
  {
    options: Array<BookingOption_.Default>;
    additional?: {
      bikeStations?: Array<BikeStation_.Default>;
    };
  },
  DefaultBrand
>;
export const Default = t.brand(
  t.intersection([
    t.type({
      options: t.array(BookingOption_.Default),
    }),
    t.partial({
      additional: t.partial({
        bikeStations: t.array(BikeStation_.Default),
      }),
    }),
  ]),
  (
    x,
  ): x is t.Branded<
    {
      options: Array<BookingOption_.Default>;
      additional?: {
        bikeStations?: Array<BikeStation_.Default>;
      };
    },
    DefaultBrand
  > => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}

export default Default;

// Success
