/*

undefined
Request schema for subscriptions-change-state

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';
import * as Units_ from 'src/core/components/units';
import * as ApiCommon_ from 'src/core/components/api-common';

export const schemaId =
  'http://maasglobal.com/maas-backend/subscriptions/subscriptions-change-state/request.json';
// Default
// The purpose of this remains a mystery
export type Default = t.Branded<
  {
    customerId: Units_.IdentityId;
    userId: Units_.IdentityId;
    changeStateId: Units_.Uuid;
    headers: ApiCommon_.Headers;
  },
  DefaultBrand
>;
export const Default = t.brand(
  t.type({
    customerId: Units_.IdentityId,
    userId: Units_.IdentityId,
    changeStateId: Units_.Uuid,
    headers: ApiCommon_.Headers,
  }),
  (
    x,
  ): x is t.Branded<
    {
      customerId: Units_.IdentityId;
      userId: Units_.IdentityId;
      changeStateId: Units_.Uuid;
      headers: ApiCommon_.Headers;
    },
    DefaultBrand
  > => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}

export default Default;

// Success
