/*

undefined
Response schema for subscriptions-change-state

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';
import * as SubscriptionChangeState_ from 'src/core/components/subscriptionChangeState';

export const schemaId =
  'http://maasglobal.com/maas-backend/subscriptions/subscriptions-change-state/response.json';
// Default
// The purpose of this remains a mystery
export type Default = t.Branded<
  {
    changeState: SubscriptionChangeState_.Default;
  },
  DefaultBrand
>;
export const Default = t.brand(
  t.type({
    changeState: SubscriptionChangeState_.Default,
  }),
  (
    x,
  ): x is t.Branded<
    {
      changeState: SubscriptionChangeState_.Default;
    },
    DefaultBrand
  > => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}

export default Default;

// Success
