/*

MaaS customer schema

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';
import * as Units_ from 'src/core/components/units';

export const schemaId = 'http://maasglobal.com/core/customer.json';

export type IdentityId = Units_.IdentityId
export const IdentityId = Units_.IdentityId
[ '/Users/twruottu/.nvm/versions/node/v10.15.3/bin/ts-node',
  '/Users/twruottu/src/maas-schemas-ts/src/converter.ts' ]
