/*

MaaS customer schema

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';
import * as Units_ from 'src/core/components/units';

export const schemaId = 'http://maasglobal.com/core/customer.json';

export type IdentityId = Units_.IdentityId
export const IdentityId = Units_.IdentityId
