/*

Product option for an itinerary, is either an existing booking pointer or a new booking instruction

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';

export const schemaId = 'http://maasglobal.com/core/product-option.json';

// Works with configurator
