/*

undefined
MaaS region schema

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';
import * as Address_ from 'components/address.json';

export const schemaId = 'http://maasglobal.com/core/region.json';
// Default
// The purpose of this remains a mystery
export type Default = t.Branded<
  {
    id: string;
    name?: string;
    countryCode: Address_.Country;
    zipCode: Address_.ZipCode;
    availability?: {};
  },
  DefaultBrand
>;
export const Default = t.brand(
  t.intersection([
    t.type({
      id: t.string,
      countryCode: Address_.Country,
      zipCode: Address_.ZipCode,
    }),
    t.partial({
      name: t.string,
      availability: t.type({}),
    }),
  ]),
  (
    x,
  ): x is t.Branded<
    {
      id: string;
      name?: string;
      countryCode: Address_.Country;
      zipCode: Address_.ZipCode;
      availability?: {};
    },
    DefaultBrand
  > => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}

export default Default;

// Success
