/*

undefined
undefined

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';
import * as UnitsGeo_ from 'components/units-geo.json';
import * as Units_ from 'components/units.json';

export const schemaId = 'http://maasglobal.com/core/stop.json';
// Default
// The purpose of this remains a mystery
export type Default = t.Branded<
  UnitsGeo_.Place & {
    startTime?: Units_.Time;
  },
  DefaultBrand
>;
export const Default = t.brand(
  t.intersection([
    UnitsGeo_.Place,
    t.partial({
      startTime: Units_.Time,
    }),
  ]),
  (
    x,
  ): x is t.Branded<
    UnitsGeo_.Place & {
      startTime?: Units_.Time;
    },
    DefaultBrand
  > => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}

export default Default;

// Success
