/*

undefined
MaaS Zendesk push notification forwarder request schema.

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';

export const schemaId =
  'http://maasglobal.com/maas-backend/webhooks/zendesk-push-notification/request.json';
// Default
// The default export. More information at the top.
export type Default = t.Branded<
  {
    devices: Array<unknown>;
    notification: {
      body?: string;
      title?: string;
      ticket_id?: string;
    };
  },
  DefaultBrand
>;
export const Default = t.brand(
  t.type({
    devices: t.array(t.unknown),
    notification: t.partial({
      body: t.string,
      title: t.string,
      ticket_id: t.string,
    }),
  }),
  (
    x,
  ): x is t.Branded<
    {
      devices: Array<unknown>;
      notification: {
        body?: string;
        title?: string;
        ticket_id?: string;
      };
    },
    DefaultBrand
  > => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}

export default Default;

// Success
