/*

undefined
MaaS Zendesk push notification forwarder response schema.

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';

export const schemaId =
  'http://maasglobal.com/maas-backend/webhooks/zendesk-push-notification/response.json';
// Default
// The default export. More information at the top.
export type Default = t.Branded<
  {
    results: unknown;
  },
  DefaultBrand
>;
export const Default = t.brand(
  t.type({
    results: t.unknown,
  }),
  (
    x,
  ): x is t.Branded<
    {
      results: unknown;
    },
    DefaultBrand
  > => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}

export default Default;

// Success
