/*

undefined
Maas Itinerary update request

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';
import * as Itinerary_ from './../../../core/itinerary';

export const schemaId =
  'http://maasglobal.com/maas-backend/itineraries/itinerary-update/response.json';
// Default
// The default export. More information at the top.
export type Default = t.Branded<
  {
    itinerary: Itinerary_.Default;
  },
  DefaultBrand
>;
export const Default = t.brand(
  t.type({
    itinerary: Itinerary_.Default,
  }),
  (
    x,
  ): x is t.Branded<
    {
      itinerary: Itinerary_.Default;
    },
    DefaultBrand
  > => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}

export default Default;

// Success
