/*

undefined
Response schema for products-providers-options

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';
import * as Provider_ from 'src/maas-backend/products/provider';

export const schemaId =
  'http://maasglobal.com/maas-backend/products/products-providers-options/response.json';
// Default
// The purpose of this remains a mystery
export type Default = t.Branded<
  {
    providers: Array<Provider_.Default>;
  },
  DefaultBrand
>;
export const Default = t.brand(
  t.type({
    providers: t.array(Provider_.Default),
  }),
  (
    x,
  ): x is t.Branded<
    {
      providers: Array<Provider_.Default>;
    },
    DefaultBrand
  > => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}

export default Default;

// Success
