/*

undefined
Response schema for subscriptions-options

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';
import * as SubscriptionOption_ from 'src/maas-backend/subscriptions/subscriptionOption';

export const schemaId =
  'http://maasglobal.com/maas-backend/subscriptions/subscriptions-options/response.json';
// Default
// The purpose of this remains a mystery
export type Default = t.Branded<
  {
    options: Array<SubscriptionOption_.Default>;
    debug?: {};
  },
  DefaultBrand
>;
export const Default = t.brand(
  t.intersection([
    t.type({
      options: t.array(SubscriptionOption_.Default),
    }),
    t.partial({
      debug: t.type({}),
    }),
  ]),
  (
    x,
  ): x is t.Branded<
    {
      options: Array<SubscriptionOption_.Default>;
      debug?: {};
    },
    DefaultBrand
  > => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}

export default Default;

// Success
