/*

undefined
Request schema for update a state of a specific booking with a TSP ID from a TSP adapter

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';
import * as Booking_ from 'src/core/booking';
import * as Configurator_ from 'src/core/components/configurator';
import * as Booking_ from '../../core/booking.json';
import * as CustomerSelection_ from 'src/core/components/customerSelection';

export const schemaId = 'http://maasglobal.com/tsp/bookings-update/request.json';
// Default
// The purpose of this remains a mystery
export type Default = t.Branded<
  {
    tspId: Booking_.TspId;
    state?: 'RESERVED' | 'ACTIVATED' | 'ON_HOLD' | 'EXPIRED';
    configurator?: Configurator_.Default;
    meta?: Booking_.Meta;
    terms?: Booking_.Terms;
    customerSelection?: CustomerSelection_.Default;
  },
  DefaultBrand
>;
export const Default = t.brand(
  t.intersection([
    t.type({
      tspId: Booking_.TspId,
    }),
    t.partial({
      state: t.union([
        t.literal('RESERVED'),
        t.literal('ACTIVATED'),
        t.literal('ON_HOLD'),
        t.literal('EXPIRED'),
      ]),
      configurator: Configurator_.Default,
      meta: Booking_.Meta,
      terms: Booking_.Terms,
      customerSelection: CustomerSelection_.Default,
    }),
  ]),
  (
    x,
  ): x is t.Branded<
    {
      tspId: Booking_.TspId;
      state?: 'RESERVED' | 'ACTIVATED' | 'ON_HOLD' | 'EXPIRED';
      configurator?: Configurator_.Default;
      meta?: Booking_.Meta;
      terms?: Booking_.Terms;
      customerSelection?: CustomerSelection_.Default;
    },
    DefaultBrand
  > => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}

export default Default;

// Success
