/*

ACRISS classification of the car, see https://en.wikipedia.org/wiki/ACRISS_Car_Classification_Code

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';
