/*

A fare/price as billed to the user in WMPs or in tokens

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';

export const schemaId = 'http://maasglobal.com/core/components/fare.json';

export type TokenId = t.Branded<string, TokenIdBrand>;
export const TokenId = t.brand(
  t.string,
  (x): x is t.Branded<string, TokenIdBrand> =>
    x.match(/^[a-z]+(-[a-z]+)*-[a-z0-9_]+$/) !== null,
  'TokenId',
);
export interface TokenIdBrand {
  readonly TokenId: unique symbol;
}
// Success
