/*

MaaS state schemas

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';

export const schemaId = 'http://maasglobal.com/core/components/state.json';

// The life-cycle state of a booking
export type BookingState = t.Branded<string, BookingStateBrand>
export const BookingState = t.brand(t.string, (x): x is t.Branded<string, BookingStateBrand> => x === x, 'BookingState')
interface BookingStateBrand {
  readonly BookingState: unique symbol
}

// The life-cycle state of a leg
export type LegState = t.Branded<string, LegStateBrand>
export const LegState = t.brand(t.string, (x): x is t.Branded<string, LegStateBrand> => x === x, 'LegState')
interface LegStateBrand {
  readonly LegState: unique symbol
}

// The life-cycle state of an itinerary
export type ItineraryState = t.Branded<string, ItineraryStateBrand>
export const ItineraryState = t.brand(t.string, (x): x is t.Branded<string, ItineraryStateBrand> => x === x, 'ItineraryState')
interface ItineraryStateBrand {
  readonly ItineraryState: unique symbol
}
