/*

Set of booking state transitions

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';

export const schemaId = 'http://maasglobal.com/core/components/state-log.json';

export type ObsoleteTime = t.Branded<string, ObsoleteTimeBrand>
export const ObsoleteTime = t.brand(t.string, (x): x is t.Branded<string, ObsoleteTimeBrand> => x === x && (x.match(/^[0-9]+$/) !== null), 'ObsoleteTime')
interface ObsoleteTimeBrand {
  readonly ObsoleteTime: unique symbol
}

