/*

MaaS booking terms and condition for its business engine

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';

export const schemaId = 'http://maasglobal.com/core/components/terms.json';

// Ticket's seat information for long distance trains, coaches or flights
