/*

MaaS common units that are used consistently within our own objects

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';

export const schemaId = 'http://maasglobal.com/core/components/units.json';

// Universally unique identifier, see https://en.wikipedia.org/wiki/Universally_unique_identifier
export type Uuid = t.Branded<string, UuidBrand>;
export const Uuid = t.brand(
  t.string,
  (x): x is t.Branded<string, UuidBrand> =>
    x === x && x.match(/^[A-Fa-f0-9]{8}(-[A-Fa-f0-9]{4}){3}-[A-Fa-f0-9]{12}$/) !== null,
  'Uuid',
);
interface UuidBrand {
  readonly Uuid: unique symbol;
}

// Uniform resource locator, see https://en.wikipedia.org/wiki/Uniform_Resource_Locator and https://mathiasbynens.be/demo/url-regex
export type Url = t.Branded<string, UrlBrand>;
export const Url = t.brand(
  t.string,
  (x): x is t.Branded<string, UrlBrand> =>
    x === x && x.match(/^(https?|ftp):\/\/[^\s/$.?#].[^\s]*$/) !== null,
  'Url',
);
interface UrlBrand {
  readonly Url: unique symbol;
}

export type Arn = t.Branded<string, ArnBrand>;
export const Arn = t.brand(
  t.string,
  (x): x is t.Branded<string, ArnBrand> =>
    x === x &&
    x.match(/^arn:aws:[a-z]+:[\w\-]*:\d{12}:[ \w\-]+(\/[\w\- \/]+)*/) !== null &&
    x.length >= 1 &&
    x.length <= 256,
  'Arn',
);
interface ArnBrand {
  readonly Arn: unique symbol;
}

export type IdentityId = t.Branded<string, IdentityIdBrand>;
export const IdentityId = t.brand(
  t.string,
  (x): x is t.Branded<string, IdentityIdBrand> =>
    x === x &&
    x.match(/^[aepus]{2}-[\w]{4}-\d:[a-f\d]{8}(-[a-f\d]{4}){3}-[a-f\d]{12}$/) !== null,
  'IdentityId',
);
export interface IdentityIdBrand {
  readonly IdentityId: unique symbol;
}

// Accepted monetary unit in ISO 4127 format, see https://en.wikipedia.org/wiki/ISO_4217#cite_note-1
export type Currency = t.Branded<string, CurrencyBrand>;
export const Currency = t.brand(
  t.string,
  (x): x is t.Branded<string, CurrencyBrand> => x === x,
  'Currency',
);
interface CurrencyBrand {
  readonly Currency: unique symbol;
}

export type AgencyId = t.Branded<string, AgencyIdBrand>;
export const AgencyId = t.brand(
  t.string,
  (x): x is t.Branded<string, AgencyIdBrand> =>
    x === x && x.length >= 2 && x.length <= 64,
  'AgencyId',
);
interface AgencyIdBrand {
  readonly AgencyId: unique symbol;
}

export type DeviceToken = t.Branded<string, DeviceTokenBrand>;
export const DeviceToken = t.brand(
  t.string,
  (x): x is t.Branded<string, DeviceTokenBrand> =>
    x === x && x.match(/^([A-Fa-f0-9]{2}){8,64}$/) !== null,
  'DeviceToken',
);
interface DeviceTokenBrand {
  readonly DeviceToken: unique symbol;
}

// POSIX time in milliseconds, https://en.wikipedia.org/wiki/Unix_time
export type Time = t.Branded<number, TimeBrand>;
export const Time = t.brand(
  t.number,
  (x): x is t.Branded<number, TimeBrand> =>
    x === x && x >= 1451606400 && x <= 9007199254740991 && Number.isInteger(x),
  'Time',
);
interface TimeBrand {
  readonly Time: unique symbol;
}

// duration in milliseconds (negative values permitted), https://en.wikipedia.org/wiki/Unix_time
export type Duration = t.Branded<number, DurationBrand>;
export const Duration = t.brand(
  t.number,
  (x): x is t.Branded<number, DurationBrand> =>
    x === x && x >= -9007199254740991 && x <= 9007199254740991 && Number.isInteger(x),
  'Duration',
);
interface DurationBrand {
  readonly Duration: unique symbol;
}

// Signature of a signed object
export type Signature = t.Branded<string, SignatureBrand>;
export const Signature = t.brand(
  t.string,
  (x): x is t.Branded<string, SignatureBrand> =>
    x === x && x.length >= 1 && x.length <= 1024,
  'Signature',
);
interface SignatureBrand {
  readonly Signature: unique symbol;
}

// A date in the form YYYY-MM-DD without a time component
export type IsoDate = t.Branded<string, IsoDateBrand>;
export const IsoDate = t.brand(
  t.string,
  (x): x is t.Branded<string, IsoDateBrand> =>
    x === x && x.match(/^\d{4}-\d{2}-\d{2}/) !== null,
  'IsoDate',
);
interface IsoDateBrand {
  readonly IsoDate: unique symbol;
}

// HTML string of block level content
export type HtmlBlock = t.Branded<string, HtmlBlockBrand>;
export const HtmlBlock = t.brand(
  t.string,
  (x): x is t.Branded<string, HtmlBlockBrand> => x === x,
  'HtmlBlock',
);
interface HtmlBlockBrand {
  readonly HtmlBlock: unique symbol;
}

// JSON encoded object or array
export type JsonParam = t.Branded<string, JsonParamBrand>;
export const JsonParam = t.brand(
  t.string,
  (x): x is t.Branded<string, JsonParamBrand> => x === x && x.length >= 2,
  'JsonParam',
);
interface JsonParamBrand {
  readonly JsonParam: unique symbol;
}

// First or last name of a customer (e.g. John)
export type PersonalName = t.Branded<string, PersonalNameBrand>;
export const PersonalName = t.brand(
  t.string,
  (x): x is t.Branded<string, PersonalNameBrand> =>
    x === x &&
    x.match(/^(?:\p{L})+(?:[`'´\-\.,]?\s?(?:\p{L})*)*$/) !== null &&
    x.length <= 255,
  'PersonalName',
);
interface PersonalNameBrand {
  readonly PersonalName: unique symbol;
}

// ITU-T E.164 phone number, see https://www.safaribooksonline.com/library/view/regular-expressions-cookbook/9781449327453/ch04s03.html
export type Phone = t.Branded<string, PhoneBrand>;
export const Phone = t.brand(
  t.string,
  (x): x is t.Branded<string, PhoneBrand> =>
    x === x && x.match(/^\+(?:\d){6,14}\d$/) !== null,
  'Phone',
);
interface PhoneBrand {
  readonly Phone: unique symbol;
}

// Slightly looser definition of phone number
export type RawPhone = t.Branded<string, RawPhoneBrand>;
export const RawPhone = t.brand(
  t.string,
  (x): x is t.Branded<string, RawPhoneBrand> =>
    x === x && x.match(/^\+?(?:\d){6,14}\d$/) !== null,
  'RawPhone',
);
interface RawPhoneBrand {
  readonly RawPhone: unique symbol;
}

// Rough validation of a valid e-mail address, see https://davidcel.is/posts/stop-validating-email-addresses-with-regex/
export type Email = t.Branded<string, EmailBrand>;
export const Email = t.brand(
  t.string,
  (x): x is t.Branded<string, EmailBrand> =>
    x === x && x.match(/^.+@.+\..+$/) !== null && x.length <= 64,
  'Email',
);
interface EmailBrand {
  readonly Email: unique symbol;
}
