/*

undefined
Response schema for products-providers-retrieve

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';
import * as Provider_ from 'src/maas-backend/products/provider';

export const schemaId =
  'http://maasglobal.com/maas-backend/products/products-providers-retrieve/response.json';
// Default
// The default export. More information at the top.
export type Default = t.Branded<
  {
    provider: Provider_.Default;
  },
  DefaultBrand
>;
export const Default = t.brand(
  t.type({
    provider: Provider_.Default,
  }),
  (
    x,
  ): x is t.Branded<
    {
      provider: Provider_.Default;
    },
    DefaultBrand
  > => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}

export default Default;

// Success
