/*

undefined
MaaS stations query response schema

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';
import * as Station_ from 'src/core/components/station';

export const schemaId = 'http://maasglobal.com/tsp/stations-list/response.json';
// Default
// The purpose of this remains a mystery
export type Default = t.Branded<
  {
    stations?: Array<{
      id: Station_.Id;
      code?: Station_.Code;
      name?: Station_.Name;
      location: Station_.Location;
      agencyId: Station_.AgencyId;
      services: Station_.Services;
      address?: Station_.Address;
      city?: Station_.City;
      country?: Station_.Country;
      zone?: Station_.Zone;
      platformCode?: Station_.PlatformCode;
    }>;
  },
  DefaultBrand
>;
export const Default = t.brand(
  t.partial({
    stations: t.array(
      t.intersection([
        t.type({
          id: Station_.Id,
          location: Station_.Location,
          agencyId: Station_.AgencyId,
          services: Station_.Services,
        }),
        t.partial({
          code: Station_.Code,
          name: Station_.Name,
          address: Station_.Address,
          city: Station_.City,
          country: Station_.Country,
          zone: Station_.Zone,
          platformCode: Station_.PlatformCode,
        }),
      ]),
    ),
  }),
  (
    x,
  ): x is t.Branded<
    {
      stations?: Array<{
        id: Station_.Id;
        code?: Station_.Code;
        name?: Station_.Name;
        location: Station_.Location;
        agencyId: Station_.AgencyId;
        services: Station_.Services;
        address?: Station_.Address;
        city?: Station_.City;
        country?: Station_.Country;
        zone?: Station_.Zone;
        platformCode?: Station_.PlatformCode;
      }>;
    },
    DefaultBrand
  > => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}

export default Default;

// Success
